environment:

  matrix:
    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels omnia
  - conda update -yq --all
  - conda install -yq conda-build jinja2

build: false

test_script:
  - conda build -q devtools\\conda-recipe
